Vagrant.configure(2) do |config|
  config.vm.define :nulecule_demo do | host |
    host.vm.box = "atomicapp/dev"
    host.vm.hostname = "cdk2-demo"
    host.vm.synced_folder "../", "/home/vagrant/demo", type: "rsync",
                          rsync__exclude: [ ".git/", ".#*", "*~", "*qcow*" ]

    host.vm.provision 'shell', inline: "sudo -- sh -c 'echo -e \"[epel]\\nname=epel\\nenabled=1\\nbaseurl=https://dl.fedoraproject.org/pub/epel/7/x86_64/\\ngpgcheck=0\" > /etc/yum.repos.d/epel.repo'"
    host.vm.provision 'shell', inline: "sudo yum install -y python-pip system-storage-manager python-blessings"
    host.vm.provision 'shell', inline: "docker pull devassistant/nulecule"

  end
end
