# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
  # it is important that the name of this box is "default"
  config.vm.define :default do |vagrant_host|
    # Box name
    vagrant_host.vm.box = 'rhel-server-7'
    vagrant_host.vm.hostname = "rhel-7-docker-host"

    vagrant_host.vm.synced_folder ".", "/vagrant", disabled: true
    vagrant_host.vm.synced_folder ".", "/home/vagrant/sync", disabled: true

    if Vagrant.has_plugin?('vagrant-registration')
      if ENV['SUB_USERNAME'] then vagrant_host.registration.username = ENV['SUB_USERNAME'] end
      if ENV['SUB_PASSWORD'] then vagrant_host.registration.password = ENV['SUB_PASSWORD'] end
    end                          
    
    vagrant_host.vm.provision 'shell', inline: "sudo subscription-manager repos --enable rhel-7-server-extras-rpms" 
    vagrant_host.vm.provision 'shell', inline: "sudo yum -y install bash-completion bind-utils setroubleshoot python-pip system-storage-manager"
    vagrant_host.vm.provision 'shell', inline: "sudo yum -y groupinstall 'Development Tools'"
    vagrant_host.vm.provision 'shell', inline: "sudo yum -y install docker"
    vagrant_host.vm.provision 'shell', inline: "sudo systemctl stop docker > /dev/null 2>&1 || :" #in case this isn't first run
    vagrant_host.vm.provision 'shell', inline: "sudo groupadd docker > /dev/null 2>&1 || :"
    vagrant_host.vm.provision 'shell', inline: "sudo usermod -a -G docker vagrant"
    vagrant_host.vm.provision 'shell', inline: "sudo systemctl enable docker && sudo systemctl start docker"
    vagrant_host.vm.provision 'shell', inline: "sudo chown root:docker /var/run/docker.sock"

    vagrant_host.vm.provision 'shell', inline: "sudo docker pull fedora/apache"
  end
end

